### ISSUE TITLE
Install an OS

### ISSUE THREAD

**Issue by bustawin** [eReuse/device-inventory#37] opened 2016-09-20 16:27 UTC
We should be able to install an OS (independently from the one we are using in Device Inventory), for example, by loading it into the PXE Server. An extra would be targeting an x86/x64 image depending on some factors (ex. capability of the processor), some specified in the config .ini (ex. minimum quantity of RAM).

**Comment by txapelgorri** [comment] 2016-09-21 10:03
Do you want me to mark #34 as duplicate of this one?. The idea I wanted to tell on #34 is basically the same :)

**Comment by ivilata** [comment] 2016-10-21 11:36
Closing this up in favor of the older (and more specific) #34.

**Closed by ivilata** 2016-10-21 11:36 UTC
Labels: duplicate, enhancement
